# Generated by Django 4.0 on 2022-04-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='images'),
        ),
    ]
